### PR TITLE
feat: created team member card

### PR DESCRIPTION
**Pull request by abhinandanmishra1**
Screenshot 2024-07-18 at 1 08 57 AM

Screenshot 2024-07-18 at 11 48 43 PM

- [ ] need image of every team member

### CODE REVIEW

**Comment by ShubhamVora-1206** [comment]
@abhinandanmishra1 Please add the team Logo image with the assets as well
icon

**Comment by abhinandanmishra1** [comment]
Isn't this logo very bad?

**Comment by ShubhamVora-1206** [comment]
It took 3 days to create this logo 😂. let's not spend more time on logo until other points are covered

**Comment by abhinandanmishra1** [comment]
Okay then review the pr and merge it if looks good.

**Review by ShubhamVora-1206 — APPROVED** [review]
Changes good to merge

**Pull request merged**
