### PR TITLE
Product modal update

### PR DESCRIPTION
**Pull request by abhinandanmishra1**
Screenshot 2024-07-19 at 12 28 45 PM

---

Screenshot 2024-07-19 at 12 29 00 PM

### CODE REVIEW

**Review by ShubhamVora-1206 — APPROVED** [review]
Changes are looking good

**Comment by ShubhamVora-1206** [comment]
@abhinandanmishra1 Please resolve conflicts so we can complete merge

**Comment by abhinandanmishra1** [comment]
@ShubhamVora-1206 done

**Comment by abhinandanmishra1** [comment]
@ShubhamVora-1206 review now and merge.

**Pull request merged**
